#!/usr/bin/env python3

import http.client


def main():
    conn = http.client.HTTPConnection("localhost", 8080)
    conn.request("GET", "/")
    response = conn.getresponse()
    print(response.status, response.reason)
    conn.close()


if __name__ == '__main__':
    main()
