#!/usr/bin/env python3

import http.server
import socketserver


def main():
    handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", 8080), handler) as httpd:
        print("serving at port: {}".format(8080))
        httpd.serve_forever()


if __name__ == '__main__':
    main()
